name: is_admin
description: A simple plugin to check if Flutter app is running with admin/root privileges.
version: 0.0.1
homepage: https://github.com/xxfttkx/is_admin

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: none
      linux:
        pluginClass: none
      macos:
        pluginClass: none
